services:
  caddy:
    container_name: caddy
    image: caddy:2.8.4
    networks:
      - proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./index.html:/usr/share/caddy/index.html

  vector:
    container_name: vector
    env_file:
      - vector.env
    image: timberio/vector:0.34.0-alpine
    restart: unless-stopped
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro

  # backend:
  #   container_name: backend
  #   image: node:20-alpine
  #   restart: unless-stopped
  #   working_dir: /home/node/app
  #   volumes:
  #     - ./backend:/home/node/app
  #   command: "npm start"

volumes:
  caddy-config:
  caddy-data:

networks:
  proxy:
    external: true
