services:

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    hostname: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    expose:
      - "9443"

networks:
  default:
    name: caddy_net
    external: true
